<template>
    <component :is="iconComponent" v-bind="$attrs" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import {
    Home,
    Users,
    BarChart3,
    Settings,
    Plus,
    Trash2,
    Edit,
    Search,
    Filter,
    Download,
    Upload,
    Menu,
    X,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    Star,
    Calendar,
    Clock,
    Trophy,
    Target,
    Shuffle,
    Play,
    Square,
    UserCheck,
    Eye,
    EyeOff,
    GraduationCap,
    CheckCircle,
    AlertCircle,
    Info,
    AlertTriangle,
    Sun,
    Moon,
    Database,
    LogIn,
    ArrowRight,
    BookOpen,
    TrendingUp,
    UserPlus,
    ArrowLeft,
    Edit2,
    Edit3,
    ChevronsLeft,
    ChevronsRight,
    MoreVertical,
    ScrollText,
    UserMinus,
    CircleDot,
    School,
    Settings2,
    Activity,
    Sparkles,
    List,
    Archive,
    FileSpreadsheet,
    Timer,
    Dice5,
    Pause,
    RotateCcw,
    Hourglass,
    Dices,
    Laptop,
    Tablet,
    Undo2,
    Award,
} from 'lucide-vue-next'

interface Props {
    name: string
}

const props = defineProps<Props>()

const iconMap = {
    Home: Home,
    Users: Users,
    BarChart3: BarChart3,
    Settings: Settings,
    Plus: Plus,
    Trash2: Trash2,
    Edit: Edit,
    Search: Search,
    Filter: Filter,
    Download: Download,
    Upload: Upload,
    Menu: Menu,
    X: X,
    ChevronDown: ChevronDown,
    ChevronUp: ChevronUp,
    ChevronLeft: ChevronLeft,
    ChevronRight: ChevronRight,
    Star: Star,
    Calendar: Calendar,
    Clock: Clock,
    Trophy: Trophy,
    Target: Target,
    Shuffle: Shuffle,
    Play: Play,
    Square: Square,
    UserCheck: UserCheck,
    Eye: Eye,
    EyeOff: EyeOff,
    GraduationCap: GraduationCap,
    CheckCircle: CheckCircle,
    AlertCircle: AlertCircle,
    Info: Info,
    AlertTriangle: AlertTriangle,
    Sun: Sun,
    Moon: Moon,
    Database: Database,
    LogIn: LogIn,
    ArrowRight: ArrowRight,
    BookOpen: BookOpen,
    TrendingUp: TrendingUp,
    UserPlus: UserPlus,
    ArrowLeft: ArrowLeft,
    Edit2: Edit2,
    Edit3: Edit3,
    ChevronsLeft: ChevronsLeft,
    ChevronsRight: ChevronsRight,
    MoreVertical: MoreVertical,
    ScrollText: ScrollText,
    UserMinus: UserMinus,
    CircleDot: CircleDot,
    School: School,
    Settings2: Settings2,
    Activity: Activity,
    Sparkles: Sparkles,
    List: List,
    Archive: Archive,
    FileSpreadsheet: FileSpreadsheet,
    Timer: Timer,
    Dice5: Dice5,
    Pause: Pause,
    RotateCcw: RotateCcw,
    Hourglass: Hourglass,
    Dices: Dices,
    Laptop: Laptop,
    Tablet: Tablet,
    Undo2: Undo2,
    Award: Award,
}

const iconComponent = computed(() => {
    return iconMap[props.name as keyof typeof iconMap] || X
})
</script>
